### ISSUE TITLE
Possibility of reading unencrypted battle videos

### ISSUE THREAD

**Issue by iSharingan** [kwsch/KeyBV#1]
Is there any possibility of getting a stripped-down version of this converted so it can read unencrypted battle videos (as exported with JKSV/etc via homebrew)? I'd try to do it myself, but I have absolutely zero experience compiling code and would likely need to be pointed to the software (not accounting for the time to find and remove just the decryption processes and skip straight to the output)

I can supply battle videos if need be (they vary in size and thus dont work with a blank key and the regular KeyBV executable).

A simple 'no' will suffice, as well. I just haven't seen anything of the kind available as of yet.

**Comment by kwsch** [comment]
https://github.com/kwsch/pkBV

you also can just drag&drop them in PKHeX to load the teams to a box for viewing.

Pretty sure a zero key bin would work if you really wanted to still use KeyBV/KeySAV.

**Comment by iSharingan** [comment]
Thank ye kindly. I didn't want to tempt myself (or give reasonable doubt to others) by putting my saves in PKHex :P
I assume pkBV is coded in C# for compiling purposes? or is there a release I'm also not aware of?

**Comment by kwsch** [comment]
Correct, no compiled version posted, so any c# compiler will do.
